# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 375307194935438843a3da086ea1b399f17e99ec20011d173cd6c9ac2eeea4a914b662a429959c5b7ab811cd1fdf910b1bc3c7018644b2f24fb3e1d954b885cf

test:
  secret_key_base: 358428c500bb036b49fbcb55f7b41cb9043b022d49fec3403aadd55e4c75049d680eef25f9663d0524878006bc790d57655603a85d75b2242fd9414fba078eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
